# Generated by Django 5.1.2 on 2024-10-24 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta_caja', models.BooleanField(default=False)),
                ('fecha_hs_aper_caja', models.DateTimeField(verbose_name='Apertura caja')),
                ('fecha_hs_cierre_caja', models.DateTimeField(verbose_name='Cierre caja')),
                ('monto_inicial_caja', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto inicial')),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Ingreso')),
                ('total_egresos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Egreso')),
                ('total_caja', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total caja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
