# Generated by Django 5.1.2 on 2024-10-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_hs_aper_caja',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Apertura caja'),
        ),
    ]
