# Generated by Django 5.1.2 on 2024-10-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_caja_fecha_hs_aper_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='abierta_caja',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_hs_cierre_caja',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cierre caja'),
        ),
    ]
