# Generated by Django 5.1.2 on 2024-10-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_alter_caja_total_caja_alter_caja_total_egresos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_mesa', models.PositiveIntegerField()),
                ('mesa_dispnible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mesas',
                'verbose_name_plural': 'Mesass',
            },
        ),
    ]
