# Generated by Django 5.1.2 on 2024-10-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telefono_alter_user_ocupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domicilio'),
        ),
    ]
