# Generated by Django 5.1.2 on 2024-10-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocina', '0002_alter_detallepedido_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='entrega_pedido',
            new_name='pedido_listo',
        ),
    ]
