# Generated by Django 5.1.2 on 2024-11-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina', '0003_rename_entrega_pedido_pedidos_pedido_listo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('0', 'Bebida'), ('1', 'Cocina')], default='Comida', max_length=2, verbose_name='Categoria'),
        ),
    ]
