# Generated by Django 5.1.2 on 2024-11-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina', '0004_productos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('0', 'Bebida'), ('1', 'Cocina')], max_length=2, verbose_name='Categoria'),
        ),
    ]
