# Generated by Django 5.1.2 on 2024-11-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_mesas'),
        ('cocina', '0005_alter_productos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_detalle', to='cocina.pedidos'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_mesa', to='caja.mesas'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock_min_prod',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
